import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark container mx-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">Grid Challenge</header>
        <main className="container py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © By Kevoff {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}
